### ISSUE TITLE
no htmltab found in PATH after installation

### ISSUE THREAD

**Issue by maddingl** [flother/htmltab#2]
I installed it the way it is described in the README, but afterwards, I have no htmltab in my PATH.

**Comment by flother** [comment]
Hi @maddingl,

I've just tested this under Python 3.8.0 and it works for me. Here's a reproducible example that installs it into a virtual environment:

~~~bash
$ python3 -m venv ~/virtualenvs/htmltab
$ source ~/virtualenvs/htmltab/bin/activate
$ pip3 install -e git+https://github.com/flother/htmltab#egg=htmltab
$ htmltab --version
htmltab, version 0.1.0rc0
~~~

If you still have a problem, can you paste the output here?

**Comment by maddingl** [comment]
Yes, that does work. I also found that it's in $HOME/.local/bin . For whatever reason, that was not part of my PATH.
Thank you!
